# Part1: Patient data


   ## 1. Check Your Understanding

    Draw diagrams showing what variables refer to what values after each statement in the following program:

    mass = 47.5
    age = 122
    mass = mass * 2.0
    age = age - 20



## 2. Sorting Out References

What does the following program print out?
```python
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)
```


## 3. Slicing Strings

A section of an array is called a slice. We can take slices of character strings as well:
```python
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen
```
What is the value of element[:4]? What about element[4:]? Or element[:]?

What is element[-1]? What is element[-2]?

Given those answers, explain what element[1:-1] does.

## 4.Thin Slices

The expression element[3:3] produces an empty string, i.e., a string that contains no characters. If data holds our array of patient data, what does data[3:3, 4:4] produce? What about data[3:3, :]?

## 5. Make Your Own Plot

Create a plot showing the standard deviation (numpy.std) of the inflammation data for each day across all patients.

## 6. Moving Plots Around

Modify the program to display the three plots on top of one another instead of side by side.

## 7. Stacking Arrays

Arrays can be concatenated and stacked on top of one another, using NumPy’s vstack and hstack functions for vertical and horizontal stacking, respectively.
```python
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)
```


The output is:

```python
A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B =
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C =
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
```

Write some additional code that slices the first and last columns of A, and stacks them into a 3x2 array. Make sure to print the results to verify your solution.

## 7. Change In Inflammation

This patient data is longitudinal in the sense that each row represents a series of observations relating to one individual. This means that the change in inflammation over time is a meaningful concept.

The numpy.diff() function takes a NumPy array and returns the differences between two successive values along a specified axis. For example, a NumPy array that looks like this:

```python
    npdiff = numpy.array([ 0,  2,  5,  9, 14])

    Calling numpy.diff(npdiff) would do the following calculations and put the answers in another array.

    [ 2 - 0, 5 - 2, 9 - 5, 14 - 9 ]

    numpy.diff(npdiff)

    array([2, 3, 4, 5])
```
Which axis would it make sense to use this function along?

If the shape of an individual data file is (60, 40) (60 rows and 40 columns), what would the shape of the array be after you run the diff() function and why?

How would you find the largest change in inflammation for each patient? Does it matter if the change in inflammation is an increase or a decrease?

# Part2: Loops

## 8. From 1 to N

Python has a built-in function called range that creates a sequence of numbers. range can accept 1, 2, or 3 parameters.

If one parameter is given, range creates an array of that length, starting at zero and incrementing by 1. For example, range(3) produces the numbers 0, 1, 2.
If two parameters are given, range starts at the first and ends just before the second, incrementing by one. For example, range(2, 5) produces 2, 3, 4.
If range is given 3 parameters, it starts at the first one, ends just before the second one, and increments by the third one. For exmaple range(3, 10, 2) produces 3, 5, 7, 9.

Using range, write a loop that uses range to print the first 3 natural numbers.

## 9. Computing Powers With Loops

Exponentiation is built into Python:
```python
print(5 ** 3)

125
```
Write a loop that calculates the same result as 5 ** 3 using multiplication (and without exponentiation).

## 10. Reverse a String

Knowing that two strings can be concatenated using the + operator, write a loop that takes a string and produces a new string with the characters in reverse order, so 'Newton' becomes 'notweN'.

# Part3: Lists

## 11. Turn a String Into a List

Use a for-loop to convert the string “hello” into a list of letters:

["h", "e", "l", "l", "o"]

Hint: You can create an empty list like this:

my_list = []



## 12. Slicing From the End

Use slicing to access only the last four characters of a string or entries of a list.
```python
string_for_slicing = "Observation date: 02-Feb-2013"
list_for_slicing = [["fluorine", "F"], ["chlorine", "Cl"], ["bromine", "Br"], ["iodine", "I"], ["astatine", "At"]]

"2013"
[["chlorine", "Cl"], ["bromine", "Br"], ["iodine", "I"], ["astatine", "At"]]
```
Would your solution work regardless of whether you knew beforehand the length of the string or list (e.g. if you wanted to apply the solution to a set of lists of different lengths)? If not, try to change your approach to make it more robust.

## 13. Non-Continuous Slices

So far we’ve seen how to use slicing to take single blocks of successive entries from a sequence. But what if we want to take a subset of entries that aren’t next to each other in the sequence?

You can achieve this by providing a third argument to the range within the brackets, called the step size. The example below shows how you can take every third entry in a list:
```python
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
subset = primes[0:12:3]
print("subset", subset)

subset [2, 7, 17, 29]
```
Notice that the slice taken begins with the first entry in the range, followed by entries taken at equally-spaced intervals (the steps) thereafter. If you wanted to begin the subset with the third entry, you would need to specify that as the starting point of the sliced range:
```python
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
subset = primes[2:12:3]
print("subset", subset)

subset [5, 13, 23, 37]
```
Use the step size argument to create a new string that contains only every other character in the string “In an octopus’s garden in the shade”
```python
beatles = "In an octopus's garden in the shade"

I notpssgre ntesae
```


## 14. Overloading

'+' usually means addition, but when used on strings or lists, it means “concatenate”. Given that, what do you think the multiplication operator * does on lists? In particular, what will be the output of the following code?
```python
counts = [2, 4, 6, 8, 10]
repeats = counts * 2
print(repeats)
```
Possible answers:
```python
    [2, 4, 6, 8, 10, 2, 4, 6, 8, 10]
    [4, 8, 12, 16, 20]
    [[2, 4, 6, 8, 10],[2, 4, 6, 8, 10]]
    [2, 4, 6, 8, 10, 4, 8, 12, 16, 20]
```
The technical term for this is operator overloading: a single operator, like + or *, can do different things depending on what it’s applied to.

# Part4: Multiple Files

## 15. Generate Composite Statistics

Use each of the files once to generate a dataset containing values averaged over all patients. This is the structure you should be using:
```python
filenames = glob.glob('inflammation*.csv')
composite_data = numpy.zeros((60,40))
for f in filenames:
    # sum each new file's data into composite_data as it's read
    #
# and then divide the composite_data by number of samples
composite_data /= len(filenames)
```
Then use pyplot to generate average, max, and min for all patients.

# Part5: Conditionals

## 16. How Many Paths?

Consider this code:
```python
if 4 > 5:
    print('A')
elif 4 == 5:
    print('B')
elif 4 < 5:
    print('C')
```
Which of the following would be printed if you were to run this code? Why did you pick this answer?

    A
    B
    C
    B and C


## 17. What Is Truth?

True and False booleans are not the only values in Python that are true and false. In fact, any value can be used in an if or elif. After reading and running the code below, explain what the rule is for which values are considered true and which are considered false.
```python
    if '':
        print('empty string is true')
    if 'word':
        print('word is true')
    if []:
        print('empty list is true')
    if [1, 2, 3]:
        print('non-empty list is true')
    if 0:
        print('zero is true')
    if 1:
        print('one is true')
```


## 18. That’s Not Not What I Meant

Sometimes it is useful to check whether some condition is not true. The Boolean operator not can do this explicitly. After reading and running the code below, write some if statements that use not to test the rule that you formulated in the previous challenge.
```python
    if not '':
        print('empty string is not true')
    if not 'word':
        print('word is not true')
    if not not True:
        print('not not True is true')
```


## 19. Close Enough

Write some conditions that print True if the variable a is within 10% of the variable b and False otherwise. Compare your implementation with your partner’s: do you get the same answer for all possible pairs of numbers?

## 20. In-Place Operators

Python (and most other languages in the C family) provides in-place operators that work like this:
```python
x = 1  # original value
x += 1 # add one to x, assigning result back to x
x *= 3 # multiply x by 3
print(x)
```


## 21. Counting Vowels

Write a loop that counts the number of vowels in a character string.
Test it on a few individual words and full sentences.
Once you are done, compare your solution to your neighbor’s. Did you make the same decisions about how to handle the letter ‘y’ (which some people think is a vowel, and some do not)?
